### PR TITLE
docs: write code of conduct

### LINKED ISSUE #1: Write up code of conduct
At minimum, we believe that a good/effective code of conduct should include:

- A Statement on diversity and inclusivity
- Details on expected, and unacceptable behaviour
- A list of consequences for unacceptable behaviour
- A procedure for reporting and dealing with unacceptable behaviour

### PR DESCRIPTION
**Pull request by mel-liow**

### CODE REVIEW

**Review by LukeAC — CHANGES_REQUESTED** [review]
Rejecting this PR for now, not enough detail in document. We'll revise as a group before merging.

**Comment by mel-liow** [comment]
> Rejecting this PR for now, not enough detail in document. We'll revise as a group before merging.

Don't worry @LukeAC, this PR is currently in `Draft` at the moment and not totally ready to be reviewed yet.

**Comment by LukeAC** [comment]
[CODE_OF_CONDUCT.md](https://github.com/UBC-MDS/DSCI_522_group20/files/7560662/CODE_OF_CONDUCT.md)
Something like this is much better @mel-liow

**Review by LukeAC — APPROVED** [review]
Looks good to me!

**Pull request merged**
