### PR TITLE
docs: update flowchart to readme file

### PR DESCRIPTION
**Pull request by nobbynguyen**
I've created a flowchart. Please let me know if revision is needed.

### CODE REVIEW

**Review by mel-liow — COMMENTED** [review]
Thanks Nobby! Could you add a screenshot of the png file? It doesn't seem to render on github

**Comment by nobbynguyen** [comment]
flowchart

**Comment by nobbynguyen** [comment]
@mel-liow  can you see the flowchart now?

**Comment by mel-liow** [comment]
Thanks, this looks great! Could you also add the /download_datasets.py too?
Also, i think the output csv is called: `stat_tests_output.csv`
Then the last part can just be `/reports` and 'Jupyter Book' - it's not a script - it's a line to run the build in terminal (results.ipynb is a section of the report, not the report itself)

**Comment by nobbynguyen** [comment]
flowchart

**Review by mel-liow — APPROVED** [review]
Great!

**Pull request merged**
