### PR TITLE
Feat: update introduction

### PR DESCRIPTION
**Pull request by mel-liow**

### CODE REVIEW

**Comment by mel-liow** [comment]
@nobbynguyen I have added an introduction (athough still WIP) but it'd be great if you could take a look at fill out the section on data cleaning please!

**Comment by mel-liow** [comment]
@LukeAC @MaeveShi @nobbynguyen  ready for review!
Note: methodology is still WIP but will be addressed in a separate PR. @nobbynguyen I've moved the section on data cleaning into `methdology.md` which should be a separate PR to this one - if you could make that PR that would be great.

Screenshot 2021-11-26 at 09 10 55

**Review by LukeAC — APPROVED** [review]

**Comment by nobbynguyen** [comment]
I will take the part of data cleaning in `methodology.md.`

**Comment by nobbynguyen** [comment]
Oh I think I should only review the changes instead of merging the commit. My bad. I just figure out how to review after I merged the commit. Please let me know if I need to revert this update.

**Pull request merged**
